[
  "rawDataFixture_1",
  [
    "",
    {
      vegetableName: "betterave rouge vrac",
      quatity: 5,
      unit: "kg",
      place: "h",
      customer: "rawDataFixture_1",
    },
    "",
    {
      vegetableName: "tomate ancienne en mélange",
      quatity: 40,
      unit: "kg",
      place: "s",
      customer: "rawDataFixture_1",
    },
    {
      vegetableName: "tomate cerise multicolore",
      quatity: 10,
      unit: "b",
      place: "s",
      customer: "rawDataFixture_1",
    },
    {
      vegetableName: "aubergine",
      quatity: 18,
      unit: "kg",
      place: "s",
      customer: "rawDataFixture_1",
    },
    {
      vegetableName: "aubergine graffiti",
      quatity: 6,
      unit: "kg",
      place: "s",
      customer: "rawDataFixture_1",
    },
    {
      vegetableName: "concombre",
      quatity: 96,
      unit: "p",
      place: "s",
      customer: "rawDataFixture_1",
    },
    {
      vegetableName: "courgette verte gros calibre",
      quatity: 30,
      unit: "kg",
      place: "s",
      customer: "rawDataFixture_1",
    },
    {
      vegetableName: "pdt conservation « desirée »super promo",
      quatity: 20,
      unit: "kg",
      place: "s",
      customer: "rawDataFixture_1",
    },
    "",
    {
      vegetableName: "carotte nouvelle botte",
      quatity: 12,
      unit: "b",
      place: "t",
      customer: "rawDataFixture_1",
    },
    {
      vegetableName: "poivron blanc",
      quatity: 5,
      unit: "kg",
      place: "t",
      customer: "rawDataFixture_1",
    },
    {
      vegetableName: "carotte nouvelle vrac non lavée",
      quatity: 16,
      unit: "kg",
      place: "t",
      customer: "rawDataFixture_1",
    },
    {
      vegetableName: "basilic panaché",
      quatity: 12,
      unit: "b",
      place: "t",
      customer: "rawDataFixture_1",
    },
    {
      vegetableName: "persil",
      quatity: 12,
      unit: "b",
      place: "t",
      customer: "rawDataFixture_1",
    },
  ],
  "rawDataFixture_2",
  [
    "",
    {
      vegetableName: "basilic vert",
      quatity: 12,
      unit: "b",
      place: "a",
      customer: "rawDataFixture_2",
    },
    "",
    {
      vegetableName: "pomme de terre primeur",
      quatity: 20,
      unit: "kg",
      place: "h",
      customer: "rawDataFixture_2",
    },
    {
      vegetableName: "betterave rouge vrac",
      quatity: 5,
      unit: "kg",
      place: "h",
      customer: "rawDataFixture_2",
    },
    {
      vegetableName: "oignon rouge",
      quatity: 8,
      unit: "b",
      place: "h",
      customer: "rawDataFixture_2",
    },
    "",
    {
      vegetableName: "melon",
      quatity: 24,
      unit: "p",
      place: "s",
      customer: "rawDataFixture_2",
    },
    {
      vegetableName: "tomate ancienne en mélange",
      quatity: 40,
      unit: "kg",
      place: "s",
      customer: "rawDataFixture_2",
    },
    {
      vegetableName: "tomate noire",
      quatity: 20,
      unit: "kg",
      place: "s",
      customer: "rawDataFixture_2",
    },
    {
      vegetableName: "tomate rose de berne",
      quatity: 20,
      unit: "kg",
      place: "s",
      customer: "rawDataFixture_2",
    },
    {
      vegetableName: "tomate coeur de bœuf",
      quatity: 20,
      unit: "kg",
      place: "s",
      customer: "rawDataFixture_2",
    },
    {
      vegetableName: "tomate cerise rouge",
      quatity: 10,
      unit: "b",
      place: "s",
      customer: "rawDataFixture_2",
    },
    {
      vegetableName: "tomate cerise multicolore",
      quatity: 10,
      unit: "b",
      place: "s",
      customer: "rawDataFixture_2",
    },
    {
      vegetableName: "aubergine",
      quatity: 12,
      unit: "kg",
      place: "s",
      customer: "rawDataFixture_2",
    },
    {
      vegetableName: "aubergine graffiti",
      quatity: 6,
      unit: "kg",
      place: "s",
      customer: "rawDataFixture_2",
    },
    {
      vegetableName: "concombre",
      quatity: 96,
      unit: "p",
      place: "s",
      customer: "rawDataFixture_2",
    },
    {
      vegetableName: "courgette verte",
      quatity: 42,
      unit: "kg",
      place: "s",
      customer: "rawDataFixture_2",
    },
    "",
    {
      vegetableName: "carotte nouvelle botte",
      quatity: 12,
      unit: "b",
      place: "t",
      customer: "rawDataFixture_2",
    },
    {
      vegetableName: "poivron vert long",
      quatity: 5,
      unit: "kg",
      place: "t",
      customer: "rawDataFixture_2",
    },
  ],
  "rawDataFixture_3",
  [
    "",
    {
      vegetableName: "basilic vert",
      quatity: 1,
      unit: "b",
      place: "a",
      customer: "rawDataFixture_3",
    },
    {
      vegetableName: "persil",
      quatity: 1,
      unit: "b",
      place: "a",
      customer: "rawDataFixture_3",
    },
    "",
    {
      vegetableName: "pomme de terre primeur",
      quatity: 5,
      unit: "kg",
      place: "h",
      customer: "rawDataFixture_3",
    },
    {
      vegetableName: "betterave rouge vrac",
      quatity: 1,
      unit: "kg",
      place: "h",
      customer: "rawDataFixture_3",
    },
    {
      vegetableName: "betterave chiogga vrac",
      quatity: 1,
      unit: "kg",
      place: "h",
      customer: "rawDataFixture_3",
    },
    {
      vegetableName: "chou rouge",
      quatity: 2,
      unit: "p",
      place: "h",
      customer: "rawDataFixture_3",
    },
    {
      vegetableName: "salade batavia",
      quatity: 6,
      unit: "p",
      place: "h",
      customer: "rawDataFixture_3",
    },
    {
      vegetableName: "salade fdc verte",
      quatity: 6,
      unit: "p",
      place: "h",
      customer: "rawDataFixture_3",
    },
    "",
    {
      vegetableName: "tomate ancienne en mélange",
      quatity: 5,
      unit: "kg",
      place: "s",
      customer: "rawDataFixture_3",
    },
    {
      vegetableName: "tomate rouge",
      quatity: 8,
      unit: "kg",
      place: "s",
      customer: "rawDataFixture_3",
    },
    {
      vegetableName: "tomate cerise rouge",
      quatity: 12,
      unit: "b",
      place: "s",
      customer: "rawDataFixture_3",
    },
    {
      vegetableName: "aubergine",
      quatity: 3,
      unit: "kg",
      place: "s",
      customer: "rawDataFixture_3",
    },
    {
      vegetableName: "concombre",
      quatity: 15,
      unit: "p",
      place: "s",
      customer: "rawDataFixture_3",
    },
    {
      vegetableName: "melon",
      quatity: 12,
      unit: "p",
      place: "s",
      customer: "rawDataFixture_3",
    },
    {
      vegetableName: "courgette verte gros calibre",
      quatity: 5,
      unit: "kg",
      place: "s",
      customer: "rawDataFixture_3",
    },
    {
      vegetableName: "courgette verte",
      quatity: 5,
      unit: "kg",
      place: "s",
      customer: "rawDataFixture_3",
    },
    {
      vegetableName: "pdt conservation « desirée »super promo",
      quatity: 20,
      unit: "kg",
      place: "s",
      customer: "rawDataFixture_3",
    },
    "",
    {
      vegetableName: "carotte nouvelle botte",
      quatity: 4,
      unit: "b",
      place: "t",
      customer: "rawDataFixture_3",
    },
    {
      vegetableName: "chou rave",
      quatity: 5,
      unit: "p",
      place: "t",
      customer: "rawDataFixture_3",
    },
    {
      vegetableName: "carotte nouvelle vrac non lavée",
      quatity: 20,
      unit: "kg",
      place: "t",
      customer: "rawDataFixture_3",
    },
  ],
  "TOTAL",
  [
    "",
    {
      vegetableName: "basilic vert",
      quatity: 13,
      unit: "b",
      place: "a",
      customer: "TOTAL",
    },
    "",
    {
      vegetableName: "betterave rouge vrac",
      quatity: 11,
      unit: "kg",
      place: "h",
      customer: "TOTAL",
    },
    {
      vegetableName: "pomme de terre primeur",
      quatity: 25,
      unit: "kg",
      place: "h",
      customer: "TOTAL",
    },
    {
      vegetableName: "oignon rouge",
      quatity: 8,
      unit: "b",
      place: "h",
      customer: "TOTAL",
    },
    {
      vegetableName: "betterave chiogga vrac",
      quatity: 1,
      unit: "kg",
      place: "h",
      customer: "TOTAL",
    },
    {
      vegetableName: "chou rouge",
      quatity: 2,
      unit: "p",
      place: "h",
      customer: "TOTAL",
    },
    {
      vegetableName: "salade batavia",
      quatity: 6,
      unit: "p",
      place: "h",
      customer: "TOTAL",
    },
    {
      vegetableName: "salade fdc verte",
      quatity: 6,
      unit: "p",
      place: "h",
      customer: "TOTAL",
    },
    "",
    {
      vegetableName: "tomate ancienne en mélange",
      quatity: 85,
      unit: "kg",
      place: "s",
      customer: "TOTAL",
    },
    {
      vegetableName: "tomate cerise multicolore",
      quatity: 20,
      unit: "b",
      place: "s",
      customer: "TOTAL",
    },
    {
      vegetableName: "aubergine",
      quatity: 33,
      unit: "kg",
      place: "s",
      customer: "TOTAL",
    },
    {
      vegetableName: "aubergine graffiti",
      quatity: 12,
      unit: "kg",
      place: "s",
      customer: "TOTAL",
    },
    {
      vegetableName: "concombre",
      quatity: 207,
      unit: "p",
      place: "s",
      customer: "TOTAL",
    },
    {
      vegetableName: "courgette verte gros calibre",
      quatity: 35,
      unit: "kg",
      place: "s",
      customer: "TOTAL",
    },
    {
      vegetableName: "pdt conservation « desirée »super promo",
      quatity: 40,
      unit: "kg",
      place: "s",
      customer: "TOTAL",
    },
    {
      vegetableName: "melon",
      quatity: 36,
      unit: "p",
      place: "s",
      customer: "TOTAL",
    },
    {
      vegetableName: "tomate noire",
      quatity: 20,
      unit: "kg",
      place: "s",
      customer: "TOTAL",
    },
    {
      vegetableName: "tomate rose de berne",
      quatity: 20,
      unit: "kg",
      place: "s",
      customer: "TOTAL",
    },
    {
      vegetableName: "tomate coeur de bœuf",
      quatity: 20,
      unit: "kg",
      place: "s",
      customer: "TOTAL",
    },
    {
      vegetableName: "tomate cerise rouge",
      quatity: 22,
      unit: "b",
      place: "s",
      customer: "TOTAL",
    },
    {
      vegetableName: "courgette verte",
      quatity: 47,
      unit: "kg",
      place: "s",
      customer: "TOTAL",
    },
    {
      vegetableName: "tomate rouge",
      quatity: 8,
      unit: "kg",
      place: "s",
      customer: "TOTAL",
    },
    "",
    {
      vegetableName: "carotte nouvelle botte",
      quatity: 28,
      unit: "b",
      place: "t",
      customer: "TOTAL",
    },
    {
      vegetableName: "poivron blanc",
      quatity: 5,
      unit: "kg",
      place: "t",
      customer: "TOTAL",
    },
    {
      vegetableName: "carotte nouvelle vrac non lavée",
      quatity: 36,
      unit: "kg",
      place: "t",
      customer: "TOTAL",
    },
    {
      vegetableName: "basilic panaché",
      quatity: 12,
      unit: "b",
      place: "t",
      customer: "TOTAL",
    },
    {
      vegetableName: "persil",
      quatity: 13,
      unit: "b",
      place: "t",
      customer: "TOTAL",
    },
    {
      vegetableName: "poivron vert long",
      quatity: 5,
      unit: "kg",
      place: "t",
      customer: "TOTAL",
    },
    {
      vegetableName: "chou rave",
      quatity: 5,
      unit: "p",
      place: "t",
      customer: "TOTAL",
    },
  ],
];
