export const rawDataFixture_3 = [
  [],
  [],
  [null, null, null, null, "EARL l'biau courtil "],
  [null, null, null, null, "producteur de légumes biologiques"],
  [null, null, null, null, "les grandes landes 14240 "],
  [null, null, null, null, "Torteval-Quesnay"],
  [null, null, null, null, null, "n° siret: 511 601 965"],
  [null, null, null, null, "mail client : earl-biaucourtil@laposte.net"],
  [],
  [],
  [],
  [null, null, null, null, "Restaurant"],
  [],
  [],
  [],
  [null, null, null, null, "région caennaise"],
  [null, null, "  "],
  [null, null, "Semaine :", null, 30, null, 2023],
  [null, null, "du", 45131, "au", 45135],
  [],
  [null, "commande / bon de livraison"],
  [
    "informations: possibilité sur demande d'avoir plus de tomates en fonction des stocks",
  ],
  [],
  [],
  [
    "types de légumes",
    "h",
    "quantité dispo",
    "prix €ht/kg*",
    null,
    "conditionnement",
    null,
    "prix€ ",
    "quantité",
    "prix en €",
  ],
  [null, null, " p =pièces /kg=kilo", null, null, "unité", null, "ht"],
  [],
  ["la saison"],
  [],
  [
    "pomme de terre primeur",
    "charlotte",
    "40kg",
    3,
    "kg",
    1,
    "kg",
    3,
    5,
    15,
    null,
    "h",
  ],
  ["carotte nouvelle botte", null, "50b", 2, "b", 1, "b", 2, 4, 8, null, "t"],
  [],
  [
    "tomate ancienne en mélange",
    null,
    "30kg",
    3.8,
    "kg",
    1,
    "kg",
    3.8,
    5,
    19,
    null,
    "s",
  ],
  [
    "tomate noire de crimée",
    null,
    "30kg",
    3.75,
    "kg",
    1,
    "kg",
    3.75,
    null,
    0,
    null,
    "s",
  ],
  [
    "tomate ananas",
    null,
    "30kg",
    3.95,
    "kg",
    1,
    "kg",
    3.95,
    null,
    0,
    null,
    "s",
  ],
  [
    "tomate coeur de bœuf",
    null,
    "30kg",
    3.7,
    "kg",
    1,
    "kg",
    3.7,
    null,
    0,
    null,
    "s",
  ],
  [
    "tomate rose de berne",
    null,
    "30kg",
    3.95,
    "kg",
    1,
    "kg",
    3.95,
    null,
    0,
    null,
    "s",
  ],
  [
    "tomate orange queen",
    null,
    "30kg",
    3.7,
    "kg",
    1,
    "kg",
    3.7,
    null,
    0,
    null,
    "s",
  ],
  ["tomate rouge", null, "20kg", 2.85, "kg", 1, "kg", 2.85, 8, 22.8, null, "s"],
  [
    "tomate cerise rouge",
    "Barquette 250gr",
    "30b",
    1.8,
    "b",
    1,
    "b",
    1.8,
    12,
    21.6,
    null,
    "s",
  ],
  [
    "tomate cerise multicolore",
    "Barquette 250gr",
    "20b",
    1.9,
    "b",
    1,
    "b",
    1.9,
    null,
    0,
    null,
    "s",
  ],
  [],
  [
    "aubergine",
    null,
    "30kg",
    2.8,
    "kg",
    1,
    "kg",
    2.8,
    3,
    8.399999999999999,
    null,
    "s",
  ],
  [
    "aubergine graffiti",
    "(bicolore)",
    "20kg",
    3,
    "kg",
    1,
    "kg",
    3,
    null,
    0,
    null,
    "s",
  ],
  [],
  ["concombre", null, "40p", 1.2, "p", 1, "p", 1.2, 15, 18, null, "s"],
  ["melon", null, "10p", 3.5, "p", 1, "p", 3.5, 12, 42, null, "s"],
  ["poivron vert long", null, "5kg", 4, "kg", 1, "kg", 4, null, 0, null, "t"],
  ["poivron blanc", null, "5kg", 5, "kg", 1, "kg", 5, null, 0, null, "t"],
  [
    "poivron couleur panaché",
    null,
    "5kg",
    5.5,
    "kg",
    1,
    "kg",
    5.5,
    null,
    0,
    null,
    "t",
  ],
  [],
  [
    "courgette verte gros calibre",
    "21+",
    "15kg",
    1.1,
    "kg",
    1,
    "kg",
    1.1,
    5,
    5.5,
    null,
    "s",
  ],
  [
    "courgette verte",
    null,
    "60kg",
    1.7000000000000002,
    "kg",
    1,
    "kg",
    1.7000000000000002,
    5,
    8.5,
    null,
    "s",
  ],
  [],
  [
    "betterave rouge botte",
    "primeur ",
    "24b",
    1.7000000000000002,
    "b",
    1,
    "b",
    1.7000000000000002,
    null,
    0,
    null,
    "h",
  ],
  [
    "betterave chiogga botte",
    "primeur ",
    "16b",
    1.9,
    "b",
    1,
    "b",
    1.9,
    null,
    0,
    null,
    "h",
  ],
  [
    "betterave rouge vrac",
    "primeur ",
    "24b",
    1.9,
    "kg",
    1,
    "kg",
    1.9,
    1,
    1.9,
    null,
    "h",
  ],
  [
    "betterave chiogga vrac",
    "primeur ",
    "16b",
    2.1,
    "kg",
    1,
    "kg",
    2.1,
    1,
    2.1,
    null,
    "h",
  ],
  [],
  ["chou kale vert", null, "30kg", 3.3, "kg", 1, "kg", 3.3, null, 0, null, "h"],
  ["chou pointu", null, "16p", 1.6, "p", 1, "p", 1.6, null, 0, null, "h"],
  ["chou rouge", null, "8p", 2.2, "p", 1, "p", 2.2, 2, 4.4, null, "h"],
  ["chou rave", null, "20p", 1.4, "p", 1, "p", 1.4, 5, 7, null, "t"],
  [],
  ["Le frais"],
  [],
  ["oignon rouge", "superbe", "60b", 2, "b", 1, "b", 2, null, 0, null, "h"],
  ["oignon jaune", null, "60b", 1.8, "b", 1, "b", 1.8, null, 0, null, "h"],
  ["échalotte botte", null, "60b", 2.4, "b", 1, "b", 2.4, null, 0, null, "h"],
  [],
  ["fenouil", null, "12kg", 4, "kg", 1, "kg", 4, null, 0, null, "t"],
  [],
  ["salade batavia", null, "18p", 0.9, "p", 1, "p", 0.9, 6, 5.4, null, "h"],
  ["salade fdc verte", null, "18p", 0.9, "p", 1, "p", 0.9, 6, 5.4, null, "h"],
  [],
  ["Le sec "],
  [],
  [
    "carotte nouvelle vrac non lavée",
    null,
    "24kg",
    2.3,
    "kg",
    1,
    "kg",
    2.3,
    20,
    46,
    null,
    "t",
  ],
  [
    "pdt conservation « desirée »super promo",
    "Chair tendre",
    "80kg",
    1,
    "kg",
    1,
    "kg",
    1,
    20,
    20,
    null,
    "s",
  ],
  [],
  ["Les aromates"],
  [],
  ["fleurs du moment", null, "80b", 0.9, "b", 1, "b", 0.9, null, 0, null, "a"],
  ["basilic vert", null, "80b", 0.9, "b", 1, "b", 0.9, 1, 0.9, null, "a"],
  ["basilic rouge", null, "48b", 0.95, "b", 1, "b", 0.95, null, 0, null, "a"],
  ["basilic citron", null, "12b", 1, "b", 1, "b", 1, null, 0, null, "a"],
  ["basilic tulsi", null, "12b", 1, "b", 1, "b", 1, null, 0, null, "a"],
  ["persil", null, "70b", 0.9, "b", 1, "b", 0.9, 1, 0.9, null, "a"],
  ["menthe verte", null, "12b", 1, "b", 1, "b", 1, null, 0, null, "a"],
  ["menthe glacial", null, "12b", 1, "b", 1, "b", 1, null, 0, null, "a"],
  ["hysope", null, "12b", 1, "b", 1, "b", 1, null, 0, null, "a"],
  ["sariette", null, "12b", 1, "b", 1, "b", 1, null, 0, null, "a"],
  ["tagette lime", null, "24b", 1, "b", 1, "b", 1, null, 0, null, "a"],
  ["perilla rouge", null, "24b", 1.1, "b", 1, "b", 1.1, null, 0, null, "a"],
  ["estragon Mexique", null, "24b", 1, "b", 1, "b", 1, null, 0, null, "a"],
  ["estragon de russie", null, "24b", 1, "b", 1, "b", 1, null, 0, null, "a"],
  ["sauge", null, "24b", 1, "b", 1, "b", 1, null, 0, null, "a"],
  ["immortelle", null, "12b", 1, "b", 1, "b", 1, null, 0, null, "a"],
  [],
  ["b/r = batavia rouge", null, null, null, null, null, null, null, null, 0],
  ["fdc /r=feuille de chêne rouge", "                                    "],
  [
    "lr/r =laitue romaine rouge",
    null,
    null,
    null,
    null,
    null,
    null,
    "total ht",
    null,
    262.80000000000007,
  ],
  [
    "dans la limite des stocks disponibles",
    null,
    null,
    null,
    null,
    null,
    "tva",
    0.055,
    null,
    14.454000000000008,
  ],
  [
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    "Total ttc ",
    null,
    277.2540000000001,
  ],
  [
    null,
    null,
    null,
    "coût de la préparation* ",
    null,
    null,
    null,
    "(?€ +tva 20%)",
  ],
  [null, null, null, "(*à négocier entre 5euros et 10 euros par client)"],
  [null, null, null, "coût de transport si inférieur au franco"],
  [null, null, null, "(50€+tva 20%)"],
  [
    "tarif 1 ,franco de port: 450€httarif 1 ,franco de port: 450€ht",
    null,
    "pour expédition",
  ],
  ["tarif 2,franco de port pour CAEN et environ "],
  ["si  vous êtes sur le trajet de livraison  déjà existant : 250€ht/semaine"],
  ["(pour une commande inférieure à 450€ , un forfait"],
  ['"traitement de commande sera facturé " à 30ht+ un forfait transport)'],
  [
    "(pour un franco inférieur à 200€ht hors trajet +30€ par livraison +15€ traitement de commande)",
  ],
  [
    "condition de vente : ",
    null,
    null,
    "le règlement se fait par chèque à la commande ",
  ],
  [null, null, null, "avec un encaissement à 30 jours après réception"],
  [null, null, null, "(sauf collectivités)"],
  [
    "coût de préparation : un surcoût peut être facturé si la demande est inférieure au conditionnement",
  ],
  [
    "les conditions de livraisons sont discutables en fonction de la localisation du site ",
  ],
  [
    "à livrer: dans tous les cas appelez nous au 06 27 33 38 26 ou au 06 61 33 69 96",
  ],
  ["pour avoir plus d'informations, nous sommes prêts à discuter "],
  [],
  [],
  [],
  [null, null, null, "      certifié par ecocert SAS à l'isle jourdain"],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
];
