import { RawData } from "core/domains/type/RawData";

export const rawDataFixture_1:RawData= [
  [],
  [],
  [null, null, null, null, "EARL l'biau courtil "],
  [null, null, null, null, "producteur de légumes biologiques"],
  [null, null, null, null, "les grandes landes 14240 "],
  [null, null, null, null, "Torteval-Quesnay"],
  [null, null, null, null, null, "n° siret: 511 601 965"],
  [null, null, null, null, "mail client : earl-biaucourtil@laposte.net"],
  [],
  [],
  [],
  [null, null, null, null, "magasin "],
  [null, null, null, null, "    spécialisé"],
  [],
  [null, null, null, null, "biocoop"],
  [null, null, null, null, "région caennaise"],
  [null, null, "  "],
  [null, null, "Semaine :", null, 30, null, 2023],
  [null, null, "du", 45131, "au", 45135],
  [],
  [null, "commande / bon de livraison"],
  [
    "informations: possibilité sur demande d'avoir plus de tomates en fonction des stocks",
  ],
  [],
  [],
  [
    "types de légumes",
    "h",
    "quantité dispo",
    "prix €ht/kg*",
    null,
    "conditionnement",
    null,
    "prix€ ",
    "quantité",
    "prix en €",
  ],
  [null, null, " p =pièces /kg=kilo", null, null, "unité", null, "ht"],
  [],
  ["la saison"],
  [
    "carotte nouvelle botte",
    null,
    "70b",
    1.85,
    "b",
    12,
    "b",
    22.200000000000003,
    1,
    22.200000000000003,
    null,
    "t",
  ],
  [
    "tomate ancienne en mélange",
    null,
    "40kg",
    3.6,
    "kg",
    5,
    "kg",
    18,
    8,
    144,
    null,
    "s",
  ],
  [
    "tomate cerise multicolore",
    "Barquette 250gr",
    "40b",
    1.75,
    "b",
    10,
    "b",
    17.5,
    1,
    17.5,
    null,
    "s",
  ],
  [
    "aubergine",
    null,
    "40kg",
    2.7,
    "kg",
    6,
    "kg",
    16.200000000000003,
    3,
    48.60000000000001,
    null,
    "s",
  ],
  [
    "aubergine graffiti",
    "(bicolore)",
    "30kg",
    2.9,
    "kg",
    6,
    "kg",
    17.4,
    1,
    17.4,
    null,
    "s",
  ],
  [
    "concombre",
    "promo",
    "96p",
    0.95,
    "p",
    12,
    "p",
    11.399999999999999,
    8,
    91.19999999999999,
    null,
    "s",
  ],
  ["poivron blanc", null, "5kg", 3.7, "kg", 5, "kg", 18.5, 1, 18.5, null, "t"],
  [
    "courgette verte gros calibre",
    "21+",
    "15kg",
    1.1,
    "kg",
    10,
    "kg",
    11,
    3,
    33,
    null,
    "s",
  ],
  [
    "betterave rouge vrac",
    "primeur ",
    "50kg",
    2.2,
    "kg",
    5,
    "kg",
    11,
    1,
    11,
    null,
    "h",
  ],
  ["Le sec "],
  [
    "carotte nouvelle vrac non lavée",
    null,
    "24kg",
    2,
    "kg",
    8,
    "kg",
    16,
    2,
    32,
    null,
    "t",
  ],
  [
    "pdt conservation « desirée »super promo",
    "Chair tendre",
    "80kg",
    1,
    "kg",
    10,
    "kg",
    10,
    2,
    20,
    null,
    "s",
  ],
  ["Les aromates"],
  [
    "basilic panaché",
    "3 variétés",
    "24b",
    0.95,
    "b",
    12,
    "b",
    11.399999999999999,
    1,
    11.399999999999999,
    null,
    "t",
  ],
  ["persil", null, "24b", 0.9, "b", 12, "b", 10.8, 1, 10.8, null, "t"],
  ["b/r = batavia rouge", null, null, null, null, null, null, null, null, 0],
  ["fdc /r=feuille de chêne rouge", "                                    "],
  [
    "lr/r =laitue romaine rouge",
    null,
    null,
    null,
    null,
    null,
    null,
    "total ht",
    null,
    477.6,
  ],
  [
    "dans la limite des stocks disponibles",
    null,
    null,
    null,
    null,
    null,
    "tva",
    0.055,
    null,
    26.267999999999972,
  ],
  [null, null, null, null, null, null, null, "Total ttc ", null, 503.868],
  [
    null,
    null,
    null,
    "coût de la préparation* ",
    null,
    null,
    null,
    "(?€ +tva 20%)",
  ],
  [null, null, null, "(*à négocier entre 5euros et 10 euros par client)"],
  [null, null, null, "coût de transport si inférieur au franco"],
  [null, null, null, "(50€+tva 20%)"],
  [
    "tarif 1 ,franco de port: 450€httarif 1 ,franco de port: 450€ht",
    null,
    "pour expédition",
  ],
  ["tarif 2,franco de port pour CAEN et environ "],
  ["si  vous êtes sur le trajet de livraison  déjà existant : 250€ht/semaine"],
  ["(pour une commande inférieure à 450€ , un forfait"],
  ['"traitement de commande sera facturé " à 30ht+ un forfait transport)'],
  [
    "(pour un franco inférieur à 200€ht hors trajet +30€ par livraison +15€ traitement de commande)",
  ],
  [
    "condition de vente : ",
    null,
    null,
    "le règlement se fait par chèque à la commande ",
  ],
  [null, null, null, "avec un encaissement à 30 jours après réception"],
  [null, null, null, "(sauf collectivités)"],
  [
    "coût de préparation : un surcoût peut être facturé si la demande est inférieure au conditionnement",
  ],
  [
    "les conditions de livraisons sont discutables en fonction de la localisation du site ",
  ],
  [
    "à livrer: dans tous les cas appelez nous au 06 27 33 38 26 ou au 06 61 33 69 96",
  ],
  ["pour avoir plus d'informations, nous sommes prêts à discuter "],
  [],
  [],
  [],
  [null, null, null, "      certifié par ecocert SAS à l'isle jourdain"],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
];
